const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  fetchEvents: () => ipcRenderer.invoke('fetch-events'),
  onRefresh: (cb) => ipcRenderer.on('refresh-events', cb),
  onConfigUpdated: (cb) => ipcRenderer.on('config-updated', (ev, cfg) => cb(cfg)),
  onToggleCollapse: (cb) => ipcRenderer.on('toggle-collapse', cb),
  listConfig: () => ipcRenderer.invoke('list-config'),
  acceptTerms: () => ipcRenderer.invoke('accept-terms'),
  openMain: () => ipcRenderer.invoke('open-main'),
  openHome: () => ipcRenderer.invoke('open-home'),
  setConfig: (cfg) => ipcRenderer.invoke('set-config', cfg),
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (cfg) => ipcRenderer.invoke('save-config', cfg),
  openUrl: (url) => ipcRenderer.invoke('open-url', url),
  openTutorial: () => ipcRenderer.invoke('open-tutorial'),
  reportHomeSize: (size) => ipcRenderer.invoke('home-resize', size),
  addIcal: (url) => ipcRenderer.invoke('add-ical', url),
  setClickThrough: (which, enabled) => ipcRenderer.invoke('set-click-through', which, enabled),
  moveWindowBy: (dx, dy) => ipcRenderer.invoke('move-window-by', dx, dy),
  getContentSize: (windowName) => ipcRenderer.invoke('get-content-size', windowName),
  toggleVisibility: (windowName) => ipcRenderer.invoke('toggle-visibility', windowName),
  minimizeWindow: (windowName) => ipcRenderer.invoke('minimize-window', windowName),
  toggleMaximizeWindow: (windowName) => ipcRenderer.invoke('toggle-maximize-window', windowName),
  closeWindow: (windowName) => ipcRenderer.invoke('close-window', windowName),
});